---
version: '2.3'
services:

  certool:
    container_name: certool
    hostname: certool
    image: rchicoli/elasticsearch:5-alpine.ssl
    volumes:
      - certs:/certool:rw
      - ../config/certool.yml:/usr/share/elasticsearch/config/x-pack/certool.yml:ro
    command: >
      sh -c '
        if ! test -d /certool/ca; then
          ./bin/x-pack/certgen --in certool.yml --out /tmp/certificate-bundle.zip
          unzip /tmp/certificate-bundle.zip -d /certool
        fi
      '
  # '

  elasticsearch:
    image: elasticsearch:alpine
    container_name: elasticsearch
    hostname: elasticsearch
    # restart: 'unless-stopped'
    expose:
      - 9200
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      development:
        aliases:
          - elasticsearch
        ipv4_address: 172.31.0.2
    # TODO: configure heap size config
    mem_limit: 2000M
    # cpu_percent: 10

  webapper:
    image: rchicoli/webapper
    container_name: webapper
    hostname: webapper
    expose:
      - 8080
    depends_on:
      - elasticsearch
    # restart: 'unless-stopped'
    networks:
      development:
        aliases:
          - webapper
        ipv4_address: 172.31.0.3
    logging:
      driver: 'rchicoli/docker-log-elasticsearch:development'
      options:
        elasticsearch-url: 'http://172.31.0.2:9200'
        elasticsearch-bulk-flush-interval: '1s'

  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: 'unless-stopped'
    hostname: nginx
    volumes:
      - ../config/nginx/ssl:/etc/nginx/ssl
      - ../config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 443
    networks:
      development:
        aliases:
          - nginx
        ipv4_address: 172.31.0.4


networks:
  development:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/24

volumes:
  certs:
    driver: local